Vagrant.configure("2") do |config|
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "generic/ubuntu2204"
    jenkins.vm.boot_timeout = 180

    disk_file = File.expand_path("jenkins_data.vdi", __dir__)
    unless File.exist?(disk_file)
      require 'vagrant/util/subprocess'
      Vagrant::Util::Subprocess.execute("VBoxManage", "createhd", "--filename", disk_file, "--size", "10240")
    end

    jenkins.vm.network "forwarded_port", guest: 8080, host: 8080

    jenkins.vm.provider "virtualbox" do |vb|
      vb.name = "jenkins-vm"
      vb.memory = 4096
      vb.cpus = 2
      vb.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", 1,
                    "--device", 0, "--type", "hdd", "--medium", disk_file]
    end

    jenkins.vm.provision "shell", inline: <<-SHELL
      set -eux
      sudo apt-get update -y
      sudo apt-get install -y software-properties-common
      sudo add-apt-repository -y ppa:openjdk-r/ppa
      sudo apt-get update -y
      sudo apt-get install -y openjdk-21-jdk curl gnupg

      sudo update-alternatives --set java /usr/lib/jvm/java-21-openjdk-amd64/bin/java

      sudo mkfs.ext4 /dev/sdb
      sudo mkdir -p /var/lib/jenkins
      echo "/dev/sdb /var/lib/jenkins ext4 defaults 0 2" | sudo tee -a /etc/fstab
      sudo mount -a

      curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
      echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

      sudo apt-get update -y
      sudo apt-get install -y jenkins

      sudo chown -R jenkins:jenkins /var/lib/jenkins
      sudo systemctl enable jenkins
      sudo systemctl start jenkins

      #echo "Jenkins Initial Admin Password:"
      #sudo cat /var/lib/jenkins/secrets/initialAdminPassword

      # Wait until Jenkins is ready
      while ! curl -s http://localhost:8080/login >/dev/null; do echo "Waiting for Jenkins..."; sleep 10; done

      # Download Jenkins CLI
      wget http://localhost:8080/jnlpJars/jenkins-cli.jar -P /tmp
 

      # Install Terraform (v1.6.6)
      TERRAFORM_VERSION="1.11.4"
      wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip

      # Install Vagrant
      wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      sudo apt update -y && sudo apt install -y vagrant

      # Get Jenkins admin password
      ADMIN_PASS=$(sudo cat /var/lib/jenkins/secrets/initialAdminPassword)

      echo "Jenkins Initial Admin Password:"
      echo "$ADMIN_PASS"     
    SHELL
  end
end
