---
- hosts: all
  become: true
  tasks:
  - name: Install kubectl
    dnf:
      name: kubectl
      disable_excludes: kubernetes
      state: present
  
  - name: Pull kubernetes container images
    command: kubeadm config images pull
  
  - name: Initialize kubernetes cluster
    shell: kubeadm init --apiserver-advertise-address={{ node_ip }} --pod-network-cidr={{ pod_network_cidr }} --cri-socket=unix:///run/containerd/containerd.sock
    # kubeadm init --pod-network-cidr=192.168.128.0/17
    register: output
  
  - name: Save output file from master
    copy:
      content: "{{ output.stdout }}"
      dest: /tmp/kube-output.txt
  
  - name: Extract worker token
    shell: tail -n2 /tmp/kube-output.txt > /tmp/join-worker-command.sh
  
  - name: Copy join command to local file
    fetch:
      src: /tmp/join-worker-command.sh
      dest: ./_cluster_k8s_info/join-worker-command.sh
      flat: yes
  
  - name: Save admin.conf to local file
    fetch:
      src: /etc/kubernetes/admin.conf
      dest: ./_cluster_k8s_info/admin.conf
      flat: yes
