---
- hosts: all
  become: true
  tasks:
  - name: Copy join token to node
    copy:
      src: ./_cluster_k8s_info/join-worker-command.sh
      dest: /tmp/join-worker-command.sh
      owner: root
      group: root
      mode: "0777"

  - name: Add kubernetes node into the cluster
    command: sh /tmp/join-worker-command.sh