apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: online-store-test
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: ${FRONTEND_IMAGE}
      imagePullPolicy: Always
      ports:
        - containerPort: 3000
  imagePullSecrets:
    - name: regcred
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: online-store-test
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: ${BACKEND_IMAGE}
      imagePullPolicy: Always
      ports:
        - containerPort: 3001
  imagePullSecrets:
    - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: online-store-test
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: online-store-test
spec:
  selector:
    app: backend
  ports:
    - port: 3001
      targetPort: 3001